### ISSUE TITLE
create issues to support additional harmonization techniques

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/habet#12]
Ones from [fortin paper](https://pubmed.ncbi.nlm.nih.gov/28826946/)
and additionally some of the techniques from the Nan paper (cited in our preprint).

Close this when issues are opened for all techniques from Fortin and whatever cherry picked techniques we choose from Nan.

**Comment by tao558** [comment]
Split this up into a few new issues:

#18 (create issues for systematic review techniques we want to implement)
#19, #20, #21, which are all of the fortin methods we'll want to implement
