### ISSUE TITLE
Improve process for registering new harmonization techniques

### ISSUE THREAD

**Issue by tao558** [KitwareMedical/habet#23]
Currently, new harmonization classes must be placed in the `harmonization` directory of `habet`. It would be nice if these techniques could be registered without needing to place them in a specific directory.

Probably depends on #22, as I know there's some kind of entry point / plugin infrastructure with `setup.py`, but I'm not familiar with it.

**Comment by ebrahimebrahim** [comment]
One option is that if the user points to the path where their API extension lives, then you can import it from that path [using importlib](https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly).

Then again if someone wants to extend the API with their own harmonization technique, maybe they _should_ have to fork the repo and do their own thing. They would already be comfortable with python programming. And it would encourage to contribute their extension back here.

**Comment by ebrahimebrahim** [comment]
After discussion, we favor something more like the [importlib](https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly) approach. Becuase it would be nice to be able to only pip install and have the ability to use custom harmonization
