### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/habet#4]
We don't need to have the beautiful, finalized, polished readme just yet, but just a first-pass acceptable one

- correct project name
- brief description
- brief usage without diving too deep into explaining anything (e.g. a single usage example)

Later we will want a more polished readme that has some figures, a bit of explanation for how to interpret and visualize the reported results, and how to use the API to add support for a new harmonization technique. Also a link to [our preprint](https://arxiv.org/abs/2211.07869).

For now just the bulleted points above are sufficient to close this issue.

**Comment by tao558** [comment]
Corrected project name in #17
